package com.example.petscue.ui.navigation

object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val AUTH = "auth"
    const val LOGIN = "login"
    const val SIGNUP = "signup"
    const val PENDING_APPROVAL = "pending_approval"
    const val MAIN = "main"
    const val ADMIN_APPROVAL = "admin_approval"
    const val ADD_PET = "add_pet"

    const val PET_DETAIL = "pet_detail/{petId}"
    const val EDIT_PET = "edit_pet/{petId}"
    const val ADOPTION_DETAIL = "adoption_detail/{petId}"
    const val EDIT_ADOPTION_PET = "edit_adoption_pet/{petId}"
    const val POST_DETAIL = "post_detail/{postId}"
    const val MAP = "map"
    const val SELECT_PET_FOR_ALERT = "select_pet_for_alert"
    const val CREATE_ALERT = "create_alert/{petId}"
    const val CHAT_DETAIL = "chat_detail/{conversationId}"
    const val ALERT_DETAIL = "alert_detail/{petId}"
    const val MY_ALERTS = "my_alerts"
    const val ADOPTION_REQUEST = "adoption_request/{petId}"
    const val MAIN_WITH_TAB = "main?tab={tab}"

    fun mainRoute(tab: String) = "main?tab=$tab"
    fun adoptionRequestRoute(petId: String) = "adoption_request/$petId"
    fun createAlertRoute(petId: String) = "create_alert/$petId"
    fun petDetailRoute(petId: String) = "pet_detail/$petId"
    fun editPetRoute(petId: String) = "edit_pet/$petId"
    fun adoptionDetailRoute(petId: String) = "adoption_detail/$petId"
    fun editAdoptionPetRoute(petId: String) = "edit_adoption_pet/$petId"
    fun postDetailRoute(postId: String) = "post_detail/$postId"
    fun chatDetailRoute(conversationId: String) = "chat_detail/$conversationId"
    fun alertDetailRoute(petId: String) = "alert_detail/$petId"
}